In [4]:
#Importing libraries
import pandas as pd
import numpy as np

In [5]:
#Loading the dataset
cars_train=pd.read_csv(r"cars_train.csv", header=None)
cars_test=pd.read_csv(r"cars_test.csv", header=None)

In [6]:
print(cars_train.shape)
cars_train.head()

(1382, 7)


0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good

In [7]:
print(cars_test.shape)
cars_test.head()

(346, 7)


0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good

In [ ]:
#PREPROCESSING

In [8]:
#RENAMING THE COLUMNS 
cars_train.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']


In [9]:
cars_train.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [10]:
cars_test.head()

buying  maint  doors persons lug_boot safety classes
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [11]:
#CHECKING FOR NULL VALUES
cars_train.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [12]:
cars_test.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [13]:
##DROPPING THE Y VALUES FROM THE TEST DATA
cars_test.drop("classes",axis=1,inplace=True)
cars_test.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [ ]:
#CONVERTING CATEGORICAL COLUMNS TO NUMERICAL USING LABEL ENCODER

In [14]:
colname=cars_train.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [15]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    cars_train[x]=le.fit_transform(cars_train[x])

In [16]:
cars_train.head()
#acc==>0
#good==>1
#unacc==>2
#vgood==>3

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [17]:
colname=cars_test.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [18]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    cars_test[x]=le.fit_transform(cars_test[x])

In [19]:
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [20]:
#CREATING X AND Y
X=cars_train.values[:,0:-1]
Y=cars_train.values[:,-1]
Y=Y.astype(int)

In [21]:
print(X.shape)
print(Y.shape)

(1382, 6)
(1382,)


In [22]:
#SCALING THE DATA
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()
scaler.fit(X)
X= scaler.transform(X)


In [23]:
print(X)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


In [24]:
cars_train.classes.value_counts(normalize=True)

classes
2    0.693922
0    0.231548
1    0.040521
3    0.034009
Name: proportion, dtype: float64

In [25]:
#SPLITTING THE DATA INTO TRAINING AND TESTING
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.2,
                                                    random_state=10,
                                                   stratify=Y) #ensuring the class dist ratio is maintained


**Running Decision Tree model**

In [26]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10, 
                                         criterion="gini")
#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[(2, 2), (1, 1), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (3, 3), (0, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (3, 3), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2),

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 54   2   7   1]
 [  0  10   0   1]
 [  2   0 190   0]
 [  1   0   0   9]]
0.9494584837545126
              precision    recall  f1-score   support

           0       0.95      0.84      0.89        64
           1       0.83      0.91      0.87        11
           2       0.96      0.99      0.98       192
           3       0.82      0.90      0.86        10

    accuracy                           0.95       277
   macro avg       0.89      0.91      0.90       277
weighted avg       0.95      0.95      0.95       277



In [28]:
model_DT.score(X_train,Y_train)

1.0

In [29]:
model_DT.feature_importances_

array([0.22575691, 0.1787049 , 0.04779911, 0.19114065, 0.1070919 ,
       0.24950654])

In [30]:
print(list(zip(cars_train.columns[0:-1],
               model_DT.feature_importances_)))

[('buying', 0.22575691221172356), ('maint', 0.17870490262570038), ('doors', 0.047799109234795606), ('persons', 0.19114064518600815), ('lug_boot', 0.10709189508483978), ('safety', 0.24950653565693254)]


In [31]:
#VIEWING IN DATAFRAME FORMAT
sample=pd.DataFrame()

sample["Column"]=cars_train.columns[0:-1]
sample["Imp value"]=model_DT.feature_importances_

sample.sort_values("Imp value",ascending=False)

Column  Imp value
5    safety   0.249507
0    buying   0.225757
3   persons   0.191141
1     maint   0.178705
4  lug_boot   0.107092
2     doors   0.047799

In [32]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DT, feature_names=cars_train.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [34]:
#PRUNING THE TREE WITH THE HELP OF HYPER-PARAMETER TUNING
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10, 
                                         criterion="gini",
                                         splitter="best", 
                                         min_samples_leaf=3,
                                         min_samples_split=5,
                                         max_depth=10, 
                                        #max_leaf_nodes=100,
                                         # max_features=0.6
                                         )
#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)
Y_pred=model_DT.predict(X_test)
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[(2, 2), (1, 1), (1, 1), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (3, 3), (0, 0), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (3, 3), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 2), (2, 2), (0, 0), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (3, 3), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2),

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 59   2   3   0]
 [  1  10   0   0]
 [  5   0 187   0]
 [  1   0   0   9]]
0.9566787003610109
              precision    recall  f1-score   support

           0       0.89      0.92      0.91        64
           1       0.83      0.91      0.87        11
           2       0.98      0.97      0.98       192
           3       1.00      0.90      0.95        10

    accuracy                           0.96       277
   macro avg       0.93      0.93      0.93       277
weighted avg       0.96      0.96      0.96       277



In [36]:
model_DT.score(X_train,Y_train)

0.9791855203619909

In [ ]:
#USING LOGISTIC REGRESSION MODEL TO CHECK IF IT IS GOOD OR NOT IF WE ARE GETTING GOOD ACCURACY FROM DECISION TREES

In [37]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression(multi_class="multinomial")
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)

[2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 0 3 2 0 2 2 2 2 2 2 2
 2 2 2 2 0 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2
 2 2 2 2 2 0 2 2 2 3 3 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 0 2 2 2 2 0 2 2 2
 2 2 2 0 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 2 2 2 2 2 0 2
 2 2 2 2 2 2 2 0 3 2 0 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 0 2 2 0 2 0 0 2 2 2 2 2 2 2 2 0 2 0 2 2 2 2 3 2 2 0 2 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 0 0 2 2 2 2 2 2 2 2 2]


In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 10   0  51   3]
 [  3   0   8   0]
 [ 20   0 172   0]
 [  5   0   3   2]]
0.6642599277978339
              precision    recall  f1-score   support

           0       0.26      0.16      0.20        64
           1       0.00      0.00      0.00        11
           2       0.74      0.90      0.81       192
           3       0.40      0.20      0.27        10

    accuracy                           0.66       277
   macro avg       0.35      0.31      0.32       277
weighted avg       0.58      0.66      0.61       277



C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [40]:
np.set_printoptions(suppress=True)
Y_pred_prob=classifier.predict_proba(X_test)
Y_pred_prob

array([[0.14554066, 0.04328243, 0.81114999, 0.00002692],
       [0.22339026, 0.03200595, 0.72944981, 0.01515398],
       [0.50445246, 0.05505243, 0.36319272, 0.0773024 ],
       ...,
       [0.35948284, 0.05065522, 0.58694523, 0.00291671],
       [0.05357408, 0.0087715 , 0.93479504, 0.00285938],
       [0.10449981, 0.01521009, 0.87264228, 0.00764782]])

In [ ]:
#CREATING A PIPELINE OF MODELS 

In [41]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=90,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [42]:
# now, create a list with the objects 
models= [tree, knn, svm, logreg]

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

for model in models:
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred) 
    clf_report= classification_report(Y_test, Y_pred) 
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 54   2   7   1]
 [  0  10   0   1]
 [  2   0 190   0]
 [  1   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  94.94584837545126
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.84      0.89        64
           1       0.83      0.91      0.87        11
           2       0.96      0.99      0.98       192
           3       0.82      0.90      0.86        10

    accuracy                           0.95       277
   macro avg       0.89      0.91      0.90       277
weighted avg       0.95      0.95      0.95       277



[[ 56   0   8   0]
 [  6   5   0   0]
 [  4   0 188   0]
 [  4   0   2   4]]
The accuracy of the  KNeighborsClassifier  model is  91.33574007220217
Classification report:
               precision    recall  f1-score   support

           0       0.80      0.88      0.84        64
           1       1.00      0.45      0.62        11
           2       0.95      0.98      0.96       192


C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [44]:
from sklearn import svm
model_SVC=svm.SVC(kernel="rbf", gamma=0.1, C=1)
#fitting training data to the model
model_SVC.fit(X_train,Y_train)

Y_pred=model_SVC.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 45   0  19   0]
 [ 11   0   0   0]
 [ 11   0 181   0]
 [  9   0   0   1]]
0.8194945848375451
              precision    recall  f1-score   support

           0       0.59      0.70      0.64        64
           1       0.00      0.00      0.00        11
           2       0.91      0.94      0.92       192
           3       1.00      0.10      0.18        10

    accuracy                           0.82       277
   macro avg       0.62      0.44      0.44       277
weighted avg       0.80      0.82      0.80       277



C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [46]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=33, 
                               metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [47]:
int(np.sqrt(len(X_train)))

33

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 28   0  36   0]
 [  9   0   2   0]
 [  4   0 188   0]
 [  4   0   2   4]]
0.7942238267148014
              precision    recall  f1-score   support

           0       0.62      0.44      0.51        64
           1       0.00      0.00      0.00        11
           2       0.82      0.98      0.90       192
           3       1.00      0.40      0.57        10

    accuracy                           0.79       277
   macro avg       0.61      0.45      0.50       277
weighted avg       0.75      0.79      0.76       277



C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sana\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [51]:
#Doing predictions on the test data
cars_test.head()

buying  maint  doors  persons  lug_boot  safety
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [52]:
test=cars_test.values
test=scaler.transform(test)#transforming all the data into scaler that was fitted on training data
#print(test)

In [53]:
#predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier

model_DT=DecisionTreeClassifier(random_state=10, 
                                         criterion="gini",
                                         splitter="best", 
                                         min_samples_leaf=3,
                                         min_samples_split=5,
                                         max_depth=10, 
                                        #max_leaf_nodes=100,
                                         # max_features=0.6
                                         )
#min_samples_leaf, min_samples_split, max_depth, max_features, max_leaf_nodes

#fit the model on the data and predict the values
model_DT.fit(X_train,Y_train)


DecisionTreeClassifier(max_depth=10, min_samples_leaf=3, min_samples_split=5,
                       random_state=10)

In [54]:
test_pred=model_DT.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 0, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2,
       0, 0, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 3, 0, 0, 2, 2, 0, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 3, 3, 0, 0,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [55]:
#saving these predicted values as a new column in the test data and reloading the data again
cars_test=pd.read_csv(r"cars_test.csv", header=None)
cars_test.columns=['buying','maint','doors','persons',
                   'lug_boot','safety','classes']
cars_test["Pred"]=test_pred
cars_test["Pred"]=cars_test["Pred"].replace({0:"acc",1:"good",2:"unacc",
                                         3:"vgood"})
cars_test.head()

FileNotFoundError: [Errno 2] No such file or directory: 'cars_test.csv'

In [ ]:
#here we have the yactuals in test data we can create confusion metrics
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(cars_test.classes,cars_test.Pred))
print(accuracy_score(cars_test.classes,cars_test.Pred))
print(classification_report(cars_test.classes,cars_test.Pred))
#accuracy is good on testing data also but in real world we cannot do this as we do not have y_test actuals values to compare with our predicted values

In [ ]:
cars_test.to_excel("Decision Test Output.xlsx",header=True)